name: milano_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  cloud_firestore: ^4.0.2
  google_sign_in: ^5.4.2
  cached_network_image: ^3.2.1

  # flutter
  flutter_redux: ^0.10.0
  cupertino_icons: ^1.0.5
  firebase_storage: ^11.0.4

  # dart
  http: ^0.13.5
  redux: ^5.0.0
  built_value: ^8.4.1
  built_collection: ^5.1.1
  freezed_annotation: ^2.2.0
  convert: ^3.1.0
  redux_epics: ^0.15.1
  meta: ^1.7.0
  flutter_svg: ^0.22.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  built_value_generator: ^8.4.1
  freezed: any
  analyzer: any

dependency_overrides:
  rxdart: any

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/